### PR TITLE
Add PlexPy to the list of applications

### PR DESCRIPTION
**Pull request by arukaen**
Hi there! 

I'm adding PlexPy to the list of applications for dockerfiles. PlexPy is a Python based monitoring and tracking tool for Plex Media Server. Its a nice addition to monitoring your Plex server when you share it with lots of people.

### CODE REVIEW

**Comment by arukaen** [comment]
Hi there!

 Wondering if you ever saw this?

**Comment by jfrazelle** [comment]
so sorry i will test this sometime this week!

On Wed, Mar 30, 2016 at 4:59 PM, Cris <notifications@github.com> wrote:

> Hi there!
>
> Wondering if you ever saw this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/pull/112#issuecomment-203690089>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
hi so sorry this is super cool you think there is a way to do it with alpine, also again sorry for the delay

**Comment by arukaen** [comment]
@jfrazelle Not sure what happened but I deleted my fork it seems. I created a new PR with alpine as the base. https://github.com/jfrazelle/dockerfiles/pull/147

**Comment by arukaen** [comment]
**CLOSED** for https://github.com/jfrazelle/dockerfiles/pull/147

**Pull request closed without merging**
