### PR TITLE
Spotify fixes

### PR DESCRIPTION
**Pull request by dnr**
Hi,

I just tried out your spotify container and had a couple tweaks to make it work better for me:
- switched to pulseaudio instead of direct alsa (I'm using ubuntu 14/15 as my host OS)
- provide access to the private dbus that gets created automatically inside the container, so I can control spotify from the host os (the alternative would be giving spotify access to the host session dbus, which seems like a security risk and sort of defeats the purpose of containerization)
- turn the "docker run" suggestion comment into a runnable wrapper script that should work for most people.

Let me know what you think.

### CODE REVIEW

**Comment by jfrazelle** [comment]
This is great have you tried using the pulseaudio
Dockerfile I have instead. Not a big fan of multiprocess containers

On Friday, December 11, 2015, dnr <notifications@github.com> wrote:

> Hi,
>
> I just tried out your spotify container and had a couple tweaks to make it
> work better for me:
>
>    - switched to pulseaudio instead of direct alsa (I'm using ubuntu
>    14/15 as my host OS)
>    - provide access to the private dbus that gets created automatically
>    inside the container, so I can control spotify from the host os (the
>    alternative would be giving spotify access to the host session dbus, which
>    seems like a security risk and sort of defeats the purpose of
>    containerization)
>    - turn the "docker run" suggestion comment into a runnable wrapper
>    script that should work for most people.
>
> Let me know what you think.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jfrazelle/dockerfiles/pull/92
> Commit Summary
>
>    - Use pulseaudio for spotify instead of alsa.
>    - Allow access to Spotify through dbus:
>
> File Changes
>
>    - *M* spotify/Dockerfile
>    <https://github.com/jfrazelle/dockerfiles/pull/92/files#diff-0> (18)
>    - *A* spotify/run
>    <https://github.com/jfrazelle/dockerfiles/pull/92/files#diff-1> (16)
>    - *A* spotify/session-local.conf
>    <https://github.com/jfrazelle/dockerfiles/pull/92/files#diff-2> (5)
>    - *A* spotify/spotify-dbus-wrap
>    <https://github.com/jfrazelle/dockerfiles/pull/92/files#diff-3> (5)
>
> Patch Links:
>
>    - https://github.com/jfrazelle/dockerfiles/pull/92.patch
>    - https://github.com/jfrazelle/dockerfiles/pull/92.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/pull/92>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by dnr** [comment]
Hmm, interesting. So as I understand it, even if we set up the spotify container to link to a pulseaudio container, it'll still start up a local dbus daemon. Unless you share the session dbus with spotify, of course, but that's orthogonal to the pulseaudio question.

Personally, I'd actually prefer that spotify gets its own dbus daemon, since it means better isolation. As for pulseaudio, I have no particular reason to want it in a container (unlike spotify, which is closed-source), so for simplicity I plan to continue running my pulseaudio directly on the host.

For this repo, though, I could:

1. switch this PR to use the pulseaudio container (and just use my own fork myself)
2. add another version of the `run` script that uses the pulseaudio container (or maybe do it with a flag)

What do you think? Other people probably have other small differences in their setup, so there's a danger of ending up with 2^n run scripts or a giant bash monstrosity.

**Comment by dnr** [comment]
Oh, and about the Ubuntu 15.04 thing, apparently they changed something in X authorization. I couldn't get things to work with any variation of `xhost +si:localuser:...`. `xhost +local:` worked, and of course `xhost +`. But those latter ones are kind of dangerous. Using `xauth` and cookies works, though. The sed thing is something I found on stackoverflow that sets that cookie to match all hosts, otherwise the hostname discrepancy between the host and container breaks things.

**Comment by jfrazelle** [comment]
sorry i think i am gong to keep this as is for now i link just one thing in the container :)

**Pull request closed without merging**
