### PR TITLE
Update firefox, tor-browser

### PR DESCRIPTION
**Pull request by koep**
* https://blog.torproject.org/blog/tor-browser-60a4-hardened-released
* https://blog.torproject.org/blog/tor-browser-60a4-released
* https://blog.torproject.org/blog/tor-browser-554-released

### CODE REVIEW

**Comment by koep** [comment]
@jfrazelle

**Comment by koep** [comment]
oops

**Comment by jfrazelle** [comment]
you rock thanks!

**Comment by koep** [comment]
Thanks! By the way: It looks like some of your automated builds stopped working 2 months ago: https://hub.docker.com/r/jess/tor-browser/, https://hub.docker.com/r/jess/sublime-text-3/ etc. Any idea why?

**Comment by jfrazelle** [comment]
Ya I'm looking into it now :( I actually host my own registry and have
jenkins do auto builds nightly because for some reason i have too many
images for hub to handle :(

On Wed, Mar 30, 2016 at 11:56 AM, Christian <notifications@github.com>
wrote:

> Thanks! By the way: It looks like some of your automated builds stopped
> working 2 months ago: https://hub.docker.com/r/jess/tor-browser/,
> https://hub.docker.com/r/jess/sublime-text-3/ etc. Any idea why?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/pull/119#issuecomment-203580245>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
I need to figure out a way to make it read only for public people to use ;)

On Wed, Mar 30, 2016 at 12:05 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> Ya I'm looking into it now :( I actually host my own registry and have
> jenkins do auto builds nightly because for some reason i have too many
> images for hub to handle :(
>
> On Wed, Mar 30, 2016 at 11:56 AM, Christian <notifications@github.com>
> wrote:
>
>> Thanks! By the way: It looks like some of your automated builds stopped
>> working 2 months ago: https://hub.docker.com/r/jess/tor-browser/,
>> https://hub.docker.com/r/jess/sublime-text-3/ etc. Any idea why?
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/dockerfiles/pull/119#issuecomment-203580245>
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by koep** [comment]
You should totally build this kind of functionality into DCOS/Velocity!

**Comment by jfrazelle** [comment]
:D

On Wed, Mar 30, 2016 at 12:18 PM, Christian <notifications@github.com>
wrote:

> You should totally build this kind of functionality into DCOS/Velocity!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/pull/119#issuecomment-203592275>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
so my private registry is read only now at r.j3ss.co everything is signed too... so let me know if you find bugs :)

**Comment by jfrazelle** [comment]
images build every few hours

**Comment by koep** [comment]
Very cool, any plans to implement some kind of UI?

**Comment by jfrazelle** [comment]
I was thinking about it, do you know of any open source ones that are
pretty :)

On Wed, Apr 6, 2016 at 2:53 AM, Christian <notifications@github.com> wrote:

> Very cool, any plans to implement some kind of UI?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/dockerfiles/pull/119#issuecomment-206269709>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by koep** [comment]
I think this looks good. It's Dockerized too! 

https://github.com/mkuchin/docker-registry-web

**Pull request merged**
